### ISSUE TITLE
Exceptions on sniffing error

### ISSUE THREAD

**Issue by asvetlov** [elastic/elasticsearch-py-async#1]
After 2d82b1b1739ba92f4de6c3f2eb88bcac9563bc70 a next call to ElasticSearch server may raise an error if the last sniffing was failed.

As I see `elasticsearch-py` suppresses exceptions like `ConnectionError` but `elasticsearch-py-async` raises all errors (connections, timeouts, cancellations etc).
`elasticsearch-py` raises `TransportError` only as I see.

Another problem is when the library reports about problems: `elasticsearch-py` raises immediatelly but `elasticsearch-py-async` will report about problem in sniffing in the past.

I did not dig into the code too deep but maybe moving sniffing from synchronous `get_connection` into async `perform_request` makes sense?

**Comment by HonzaKral** [comment]
Thanks for raising this issue. You are absolutely right that this is inconsistent.

> `elasticsearch-py` raises immediatelly but `elasticsearch-py-async` will report about problem in sniffing in the past.

This *feels* ok to me since with async we gain the option of sniffing in the background (which I believe is better than what `elasticsearch-py` does now). Then we need to raise the error somewhere (unless we suppress it and just log it, also an option).

I think the proper solution is to change the sniffing logic wait for first *successful* request to return, ignoring the rest (just relying on the standard logging mechanism for discovery). Right now the `_get_sniff_data` method is waiting for first task to finish (via `asyncio.wait(..., return_when=asyncio.FIRST_COMPLETED)`) which will most likely be the failed request. That way the error will be very unlikely - essentially only when all the requests fail.

Another option would be to document the `invoke_sniffing` method and encourage people to run it on their own (using a timer for example) if they really care about how this is done (waiting for the future right away, letting it run on background, ...).

What do you think?

> ... moving sniffing from synchronous get_connection into async perform_request makes sense?

I am afraid I do not understand this, can you elaborate a little bit?

**Comment by HonzaKral** [comment]
I changed a bunch of things here - in 3e0aa59 I made the behavior consistent with `elasticsearch-py`: trying all the connections, only ignoring known errors (Connection and Serialization).

In 568875e I also added an option to suppress sniffing raising any errors (for people who view it as an optional background process).

The only difference now is that `elasticsearch-py` raises issues with sniffing immediately while the async version will do it at next request. This I don't know how (or indeed if) can be fixed since the sniffing is running in the background essentially.

Hope this helps
